Repository P4P-Group129-2022/frontend, pull requests merged in 2022-08, with the labels that each got.

#41 Add user functionalities
  package.json
  src/App.tsx
  src/assets/icons/chrome.png
  src/assets/icons/finder.png
  src/assets/icons/launchpad.png
  src/assets/icons/slack.png
  src/assets/icons/terminal.png
  src/assets/icons/trash.png
  src/assets/icons/vscode.png
  src/assets/wallpaper.png
  src/components/Dock/Dock.tsx
  src/components/MainContentsContainer/MainContentsContainer.tsx
  src/components/MainContentsContainer/index.js
  src/components/Notification/Notification.tsx
  src/contexts/UserContextProvider.tsx
  src/firebase/config.js
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/usePersistedState.ts
  src/pages/HomePage/HomePage.tsx
  src/types/UserTypes.ts
  yarn.lock
Labels: bug, enhancement

#43 Implement git push
  src/api/Api.ts
  src/components/Dock/Dock.tsx
  src/contexts/MessageContextProvider.tsx
  src/contexts/ScenarioContextProvider.tsx
  src/contexts/UserContextProvider.tsx
  src/hooks/useLogin.ts
  src/pages/MessagePage/MessagePage.tsx
  src/pages/ScenarioSelectPage/ScenarioSelectPage.tsx
  src/pages/TerminalPage/TerminalPage.tsx
  src/utils/TerminalCommandProcessor.ts
Labels: bug, enhancement

#45 Feature/messages
  src/components/MessageBlock/MessageBlock.tsx
  src/components/MessageInput/MessageInput.tsx
  src/contexts/MessageContextProvider.tsx
  src/contexts/ScenarioContextProvider.tsx
  src/contexts/UserContextProvider.tsx
  src/pages/MessagePage/MessagePage.tsx
  src/types/UserTypes.ts
  src/utils/TerminalCommandProcessor.ts
Labels: bug, enhancement

#47 Implement invite to org
  src/api/Api.ts
  src/contexts/ScenarioContextProvider.tsx
  src/hooks/useLogin.ts
  src/pages/OrgInvitePage/OrgInvitePage.tsx
  src/routes/Routes.tsx
  src/types/GitHubTypes.ts
Labels: enhancement

#49 Added scenario progression trigger for git push.
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/TerminalPage/TerminalPage.tsx
  src/utils/TerminalCommandProcessor.ts
Labels: enhancement

#51 Feature/link to tests
  src/components/LinkToTestsDialog/LinkToTestsDialog.tsx
  src/components/LinkToTestsDialog/index.js
  src/pages/HomePage/HomePage.tsx
Labels: enhancement

#54 Scenario progression trigger for git push
  src/api/Api.ts
  src/contexts/UserContextProvider.tsx
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/ScenarioSelectPage/ScenarioSelectPage.tsx
  src/pages/VSCodePage/VSCodePage.tsx
Labels: enhancement

#55 Feature/add git branch checkout
  src/api/Api.ts
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/TerminalPage/TerminalPage.tsx
Labels: enhancement

#57 Implement scenario progression logic
  src/api/Api.ts
  src/components/Notification/Notification.tsx
  src/contexts/ScenarioContextProvider.tsx
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/MessagePage/MessagePage.tsx
  src/pages/VSCodePage/VSCodePage.tsx
  src/types/GitHubTypes.ts
  src/types/NotificationTypes.ts
  src/types/ScenarioTypes.ts
  src/utils/TaskType.ts
Labels: enhancement

#58 Replaced hard-coded scenario details with endpoint call.
  src/api/Api.ts
  src/contexts/ScenarioContextProvider.tsx
  src/pages/ScenarioSelectPage/ScenarioSelectPage.tsx
  src/types/ScenarioTypes.ts
Labels: enhancement

#59 Implement git rebase
  src/api/Api.ts
  src/hooks/useTerminalCommandProcessor.ts
Labels: enhancement

#61 Implement new task types
  src/hooks/useTerminalCommandProcessor.ts
  src/utils/TaskType.ts
Labels: enhancement

#63 Scenario can now progress with REBASE when TaskType.REBASE is required.
  src/hooks/useTerminalCommandProcessor.ts
  src/utils/TaskType.ts
Labels: enhancement

#64 Made the notification appear for 60 seconds so that the users can tak…
  src/contexts/NotificationContextProvider.tsx
  src/contexts/ScenarioContextProvider.tsx
Labels: enhancement

#65 Organise main menu
  src/api/Api.ts
  src/components/Buttons/CustomButton.tsx
  src/components/Buttons/index.js
  src/components/InstructionsDialog/InstructionsDialog.tsx
  src/components/InstructionsDialog/index.js
  src/components/LinkToTestsDialog/LinkToTestsDialog.tsx
  src/contexts/UserContextProvider.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/TerminalPage/TerminalPage.tsx
  src/types/UserTypes.ts
Labels: bug, enhancement

#66 Add user related features
  src/api/Api.ts
  src/contexts/UserContextProvider.tsx
  src/hooks/useLogin.ts
  src/types/UserTypes.ts
Labels: bug, enhancement

#67 Added onclick to navigate back to scenario-select-page.
  src/components/Dock/Dock.tsx
Labels: enhancement

#68 Fix minor issues
  public/index.html
  src/components/InstructionsDialog/InstructionsDialog.tsx
Labels: bug

#69 Refactor hardcoded localhost value to api endpoint env var
  src/api/Api.ts
  src/pages/ScenarioSelectPage/ScenarioSelectPage.tsx
Labels: bug

#70 Rearrange scenario select
  public/index.html
  src/components/Button/Button.tsx
  src/components/Button/index.js
  src/pages/HomePage/HomePage.tsx
  src/pages/ScenarioSelectPage/ScenarioSelectPage.tsx
Labels: bug, enhancement

#71 Show actual branch in git terminal
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/TerminalPage/TerminalPage.tsx
Labels: bug, enhancement

#72 Add more detailed instruction on the homepage.
  src/pages/HomePage/HomePage.tsx
Labels: bug, documentation

#73 Fix message disappear in pr
  src/contexts/MessageContextProvider.tsx
  src/contexts/ScenarioContextProvider.tsx
  src/hooks/useChatStateWithRef.ts
  src/hooks/useTerminalCommandProcessor.ts
  src/pages/DemoPage/DemoPage.tsx
  src/pages/MessagePage/MessagePage.tsx
  src/pages/VSCodePage/VSCodePage.tsx
  src/routes/Routes.tsx
Labels: bug
